export const typography = {
  h1: {
    fontSize: "3em",
    fontWeight: "300",
    letterSpacing: "-1.5px",
    fontFamily: "'Open Sans', sans-serif",
    margin: 0,
    padding: 0,
  },
  h2: {
    fontSize: "2.5em",
    fontWeight: 300,
    letterSpacing: "-0.5px",
    fontFamily: "'Open Sans', sans-serif",
    margin: 0,
    padding: 0,
  },
  h3: {
    fontSize: "2em",
    fontWeight: 400,
    letterSpacing: "0px",
    fontFamily: "'Open Sans', sans-serif",
    margin: 0,
    padding: 0,
  },
  h4: {
    fontSize: "1.75em",
    fontWeight: 400,
    letterSpacing: "0.25px",
    fontFamily: "'Open Sans', sans-serif",
    margin: 0,
    padding: 0,
  },
  h5: {
    fontSize: "1.5em",
    fontWeight: 400,
    letterSpacing: "0px",
    fontFamily: "'Open Sans', sans-serif",
    margin: 0,
    padding: 0,
  },
  h6: {
    fontSize: "1.25em",
    fontWeight: 500,
    letterSpacing: "0.15px",
    fontFamily: "'Open Sans', sans-serif",
    margin: 0,
    padding: 0,
  },
  p: {
    fontSize: "1em",
    fontWeight: 400,
    letterSpacing: "0.15px",
    fontFamily: "'Open Sans', sans-serif",
    margin: 0,
    padding: 0,
  },
};
